name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Grant execute permission
        run: chmod +x mvnw

#      - name: Run Checkstyle
#        run: ./mvnw checkstyle:check

      - name: Run Formatter
        run: ./mvnw spring-javaformat:apply

      - name: Run PMD
        run: ./mvnw pmd:check